### PR TITLE
Fixed bug for Variational model.

### PR DESCRIPTION
**Pull request by fargolo**
Previously, calling CmdStan::stan(Stanmodel::X)
With X of type Variational() would return Error `type Variational no field save_warmup`.

Patched it by adding type checking ( `isa(x,Sample)` ) on line 248 before updating `start_sample`.

CmdStan v5.0.5
Julia 1.1.0

### CODE REVIEW

**Comment by fargolo** [comment]
I found this bug while running a `julia> stanmodel = Stanmodel(Variational(),...)` and then `stan(stanmodel,...)`.

Digging into stancode.jl, I found it was due to `model.method.save_warmup` call.
Type checking (`isa(model.method,Sample))` prevents the inadequate call

**Comment by goedman** [comment]
Hi @fargolo 

Thank you for this PR. I just merged to master this version:
```
  if model.output_format != :array
    start_sample = 1
    if isa(model.method, Sample) && !model.method.save_warmup
      start_sample = model.method.num_warmup+1
    end
    res = convert_a3d(res, cnames, Val(model.output_format);
      start=start_sample)
  end
```
Apologies for screwing this up earlier. I've also updated bernoulli_variational.jl to return an MCMCChains.Chains object and added read_summary() to test theta.

If you are ok with this, I'll close this PR in a day or so.

Thanks again,
Rob

**Comment by fargolo** [comment]
@goedman I am willing to modify the commit to get it merged to the project, since I invested time debugging the open-source code.
I changed my original fix from nested `if`s to `&&` operator.  

Also, could you add documentation explaining how to receive pull requests? I am aware that it is the path of least resistance  from a developers perspective, but it is frustrating to get PRs rewritten before merged. 

Best regards, 
Felipe

**Comment by goedman** [comment]
Felipe,

My apologies. Normally I always merge PRs first and then test, but in this case I had several updates to stancode.jl outstanding and merged your proposed change with several others. If it is important to have your PR merged we can do that in a couple of steps. Just let me know.

Of course I did give you credit for debugging and resolving this issue in Versions.md. And indeed, I'm painfully aware how time consuming it is to fix issues in CmdStan.jl!

Thanks again for your work, best,
Rob

**Comment by fargolo** [comment]
No need for setbacks.
The release citation is enough. 
Sorry to bother,
Felipe

**Pull request closed without merging**
