### PR TITLE
add init_file within stan method

### PR DESCRIPTION
**Pull request by ueliwechsler**
This PR should enable the `init` `kwarg` to work properly.
Code provided by @andrstef.

### CODE REVIEW

**Comment by goedman** [comment]
Thank you for the pull request. Do you have a MWE showing the problem? Or a description what's not working. Thanks.

**Comment by ueliwechsler** [comment]
I think there was a regression in the functionality of the `kwarg` `init` such that the `Dict` with 
 the initialization values was not assigned to the stan model
```julia
init_dict = Dict("a"=>..., ...)
stan(;... init=init_dict )
```

The regresssion occurred around or after version 5.4.

**Comment by andrstef** [comment]
in the `stan()` function, the init file(s) get produced. However, the location of the file(s) needs to be stored in the `init_file` field of the `Stanmodel`. Otherwise, parsing the command will not include the init file's location.
This somehow got lost with version 5.4. Currently, the init files are dumped but not picked  up by Cmdstan.

**Comment by goedman** [comment]
In the merge queue, should be merged as CmdStan 6.0.2 within the next 30 mins or so. Thanks again!

**Pull request closed without merging**
