### PR TITLE
optional include

### PR DESCRIPTION
**Pull request by oliverdechant**

### CODE REVIEW

**Comment by goedman** [comment]
Oliver, I'll merge it now, but wonder if it would be better to make the example using beta.1 .. beta.k.

**Comment by oliverdechant** [comment]
More to have it included for completeness, since at least one person raised it, are all of these examples soon to be outdated?

**Comment by goedman** [comment]
Not at all, CmdStan and StanDataFrames will remain pretty much as they are. StanMCMCChains.jl will go through a major update, and I'm also looking into StanMamba (mainly incorporating the old Stan.jl examples). StanMCMCChains.jl can only be released once the new TuringLang/MCMCChains.jl is merged.

**Comment by oliverdechant** [comment]
My misunderstanding then. I'll look to revisit the example and include some additional monitors. It would be fun to add more. I don't know, is it feasible to replicate from `stan-dev/example-models`?

**Comment by oliverdechant** [comment]
Never mind I see that these are the same examples.

**Comment by goedman** [comment]
I have updated your example (by adding one more beta.2 term) and merged that on master. I'll probably do a quick METADATA release of CmdStan v4.5.3 tomorrow. Just in case you're interested I've sent you an invitation to become an organizer for StanJulia.

**Comment by oliverdechant** [comment]
Thanks Rob!

**Pull request merged**
